- name: RHEL | Install GitLab GPG key
  rpm_key:
    state: present
    key: https://packages.gitlab.com/gpg.key
  when: ansible_os_family == 'RedHat'
  tags:
    - gitlab
    - gitlab-gpg

- name: RHEL | Install support packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - postfix
    - cronie
  tags:
    - gitlab
    - gitlab-packages

- name: RHEL | Install GitLab CE
  yum:
    name: gitlab-ce
    state: latest
  notify:
    - upgrade gitlab
    - restart gitlab
    - wait for unicorn
  tags:
    - gitlab
    - gitlab-update
